ansible_ssh_user: root
perform_upgrades: true
env_prefix: production
app_user: production
cron_enabled: true
admin_email: fox@vulpinity.com
domains:
 - artconomy.com
 - beta.artconomy.com
 - www.artconomy.com
 - outbound.artconomy.com
mail_domain: outbound.artconomy.com
app_version: master
host_color: red
password_protect: false