ansible_ssh_user: root
perform_upgrades: true
env_prefix: stage
app_user: stage
cron_enabled: true
admin_email: fox@vulpinity.com
domains:
 - stage.artconomy.com
mail_domain: stage_outbound.artconomy.com
app_version: master
host_color: green
password_protect: false
swap_kilo_size: 8388608
create_webhooks: true
gen_certificates: true
